# Generated by Django 4.2.1 on 2023-07-22 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sign_up', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdsPost',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('brandname', models.CharField(max_length=150, null=True)),
                ('description', models.TextField(null=True)),
                ('hashtag', models.CharField(db_index=True, max_length=150, null=True)),
                ('text', models.TextField(null=True)),
                ('image', models.ImageField(null=True, upload_to='AdsImages/')),
                ('video', models.FileField(null=True, upload_to='AdsVideos/')),
                ('audio', models.FileField(null=True, upload_to='AdsAudio/')),
                ('plan', models.CharField(db_index=True, max_length=15, null=True)),
                ('status', models.CharField(db_index=True, max_length=15, null=True)),
                ('link', models.URLField(null=True)),
                ('views', models.IntegerField(db_index=True, default=0, null=True)),
                ('clicks', models.IntegerField(default=0, null=True)),
                ('post_datetime', models.DateTimeField(db_index=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sign_up.user')),
            ],
        ),
    ]
