# Generated by Django 4.2.1 on 2023-07-23 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sign_up', '0001_initial'),
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Premium',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('plan', models.CharField(db_index=True, max_length=15, null=True)),
                ('status', models.CharField(db_index=True, max_length=15, null=True)),
                ('post_datetime', models.DateTimeField(db_index=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sign_up.user')),
            ],
        ),
    ]
