# Generated by Django 4.2.1 on 2023-07-23 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_premium'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Premium',
        ),
    ]
