# Generated by Django 4.2.1 on 2023-07-22 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sign_up', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HashtagList',
            fields=[
                ('hashtag', models.CharField(max_length=150, primary_key=True, serialize=False, unique=True)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150)),
                ('profile_image', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(null=True)),
                ('hashtag', models.CharField(db_index=True, max_length=150, null=True)),
                ('text', models.TextField(null=True)),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('video', models.FileField(null=True, upload_to='videos/')),
                ('audio', models.FileField(null=True, upload_to='audio/')),
                ('privacy', models.CharField(max_length=20)),
                ('stars', models.DecimalField(decimal_places=2, default=0, max_digits=3, null=True)),
                ('link', models.URLField(null=True)),
                ('post_datetime', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sign_up.user')),
            ],
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('hashtag', models.CharField(db_index=True, max_length=150, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sign_up.user')),
            ],
        ),
    ]
