# Generated by Django 4.2.1 on 2023-07-22 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(db_index=True, max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('profile_image', models.CharField(max_length=150)),
                ('bio', models.CharField(max_length=200)),
                ('link', models.URLField(null=True)),
                ('follower_count', models.IntegerField(default=0, null=True)),
                ('following_count', models.IntegerField(default=0, null=True)),
                ('post_count', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(max_length=6)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sign_up.user')),
            ],
        ),
    ]
